name: Publish
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Package and publish chart
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          mkdir -p /tmp/out
          helm init -c
          helm package -d /tmp/out ./cert-manager-crds

          git remote set-url origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git fetch
          git checkout gh-pages
          cp /tmp/out/* .
          helm repo index .
          git config user.name "Robot"
          git config user.email "robot@rocketeer.be"
          git add .
          git commit -a -m "Update chart repository"
          git push
